#!/bin/bash

set -euo pipefail

kubectl get cronjob bespin -o jsonpath='{.spec.schedule}' | grep -q -w '*/5 * * * *'
kubectl get cronjob bespin -o jsonpath='{.spec.jobTemplate.spec.template.spec.containers[*].command}' | grep -q -w 'date'
